stages:
- test
- report
- deploy

gtest:
   stage: test
   script:
   - make gtest

ghz-perf:
   stage: test
   script:
   - make ghz-perf-test

python:
   stage: test
   script:
   - make python

report:
   stage: report
   script:
   - make report
   artifacts:
     paths:
     - performance.html

pages:
  stage: deploy
  dependencies:
  - report
  script:
  - mkdir -p public
  - mv performance.html public/
  artifacts:
        when: on_success
        paths:
        - public
