stages:
  - git_submodule
  - test

git_submodule:
   stage: git_submodule
   script:
     - git submodule sync --recursive
     - git submodule update --init --recursive

test:
   stage: test
   script:
     - cd demo_cpp_wave && make gtest
     - cd demo_cpp_wave && make ghz-perf-test
     - cd demo_cpp_wave && make cpp-perf-test
