stages:
- git_submodule
- test
- report
- deploy

git_submodule:
   stage: git_submodule
   script:
   - git submodule sync --recursive
   - git submodule update --init --recursive

gtest:
   stage: test
   script:
   - make gtest

ghz-perf:
   stage: test
   script:
   - make ghz-perf-test

report:
   stage: report
   script:
   - make report
   paths:
   - performance.html

pages:
  stage: deploy
  dependencies:
  - inline
  script:
  - mkdir -p public
  - mv performance.html public/
  artifacts:
        when: on_success
        paths:
        - public
