stages:
  - git_submodule
  - test

git_submodule:
   stage: git_submodule
   script:
     - git submodule sync --recursive
     - git submodule update --init --recursive

gtest:
   stage: test
   script:
     - make gtest

ghz-perf:
   stage: test
   script:
     - make ghz-perf-test

cpp-perf:
   stage: test
   script:
     - make cpp-perf-test
