version: '3'
services:
  server:
    image: grpc-waves-python-server
    user: ${CURRENT_UID}
    command: /data/airy.py
    volumes:
    - ./python_server:/data
  client:
    image: grpc-waves-python-client
    user: ${CURRENT_UID}
    depends_on:
    - server
