version: '3'
services:
  server:
    build: cpp_server
    user: ${CURRENT_UID}
    entrypoint: ["/usr/wave_server", "--spectrum", "y"]
  client:
    build: ghz
    user: ${CURRENT_UID}
    depends_on:
    - server
    entrypoint: ["/usr/wait-for-it.sh", "server:50051", "--",
              "/usr/bin/ghz", "--insecure",
              "--proto", "/wave.proto",
              "--call", "wave.ElevationService.GetElevation",
              "--data", '{ "points": [
                  { "x": "1.3", "y": "2.7" },
                  { "x": "1.3", "y": "2.7" },
                  { "x": "1.3", "y": "2.7" },
                  { "x": "1.3", "y": "2.7" },
                  { "x": "1.3", "y": "2.7" },
                  { "x": "1.3", "y": "2.7" }
                ], "t": "0.1" }',
              "server:50051"]
    volumes:
    - "./:/shared"
