version: '3'
services:
  server:
    build: wave_server
    user: ${CURRENT_UID}
    entrypoint: ["/usr/wave_server", "--spectrum", "n"]
  client:
    build: wave_client
    user: ${CURRENT_UID}
    depends_on:
    - server
    entrypoint: ["/usr/wait-for-it.sh", "server:50051", "-q", "--", "time", "/usr/wave_client" , "--ip", "server", "--port", "50051"]
