version: '3'
services:
  server:
    image: "docker_sync_server:latest"
    ports:
     - "50051:50051"
  client:
    image: "docker_sync_client:latest"
    depends_on:
      - "server"
    command: ["/usr/wait-for-it.sh", "server:50051", "--", "/usr/greeter_sync_client" , "--ip", "server", "--port", "50051"]
